### ISSUE TITLE
Clicking the save button crashes the game (in Linux at least)

### ISSUE THREAD

**Issue by hazelnot** [TheAssemblyArmada/Vanilla-Conquer#196]
Just that, clicking Save Mission in the menu causes a crash. Here's the gdb log:
```
C&C95 - Scenario read OK.
C&C95 - About to call Options.Set.
C&C95 - About to return from Start_Scenario.
C&C95 - Scenario started OK.
C&C95 - Initialising message system.
C&C95 - About to call Call_Back.
*** stack smashing detected ***: terminated

Thread 1 "vanillatd" received signal SIGABRT, Aborted.
0xf7fce549 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fce549 in __kernel_vsyscall ()
#1  0xf7a0a1ea in raise () from /usr/lib32/libc.so.6
#2  0xf79f240e in abort () from /usr/lib32/libc.so.6
#3  0xf7a4eaac in __libc_message () from /usr/lib32/libc.so.6
#4  0xf7aee8cc in __fortify_fail () from /usr/lib32/libc.so.6
#5  0xf7aee89d in __stack_chk_fail () from /usr/lib32/libc.so.6
#6  0x5666c048 in __stack_chk_fail_local ()
#7  0x56659fa4 in Find_File_Data_Posix::FindNextWithFilter (this=0x56bc13c0) at /home/hazelnot/git/Vanilla-Conquer/common/file_posix.cpp:81
#8  0x5665a07b in Find_File_Data_Posix::FindFirst (this=0x56bc13c0, fname=0x56673dba "SAVEGAME.*")
    at /home/hazelnot/git/Vanilla-Conquer/common/file_posix.cpp:93
#9  0x5664f07e in Find_First (fname=0x56673dba "SAVEGAME.*", mode=0, ffblk=0xffffcc3c) at /home/hazelnot/git/Vanilla-Conquer/common/file.cpp:11
#10 0x565df6b3 in LoadOptionsClass::Fill_List (this=0xffffcf98, list=0xffffcde9) at /home/hazelnot/git/Vanilla-Conquer/tiberiandawn/loaddlg.cpp:587
#11 0x565deaf9 in LoadOptionsClass::Process (this=0xffffcf98) at /home/hazelnot/git/Vanilla-Conquer/tiberiandawn/loaddlg.cpp:250
#12 0x565b91e8 in GameOptionsClass::Process (this=0x566c4ce0 <Options>) at /home/hazelnot/git/Vanilla-Conquer/tiberiandawn/goptions.cpp:420
#13 0x5658d657 in Main_Game (argc=2, argv=0xffffd2d4) at /home/hazelnot/git/Vanilla-Conquer/tiberiandawn/conquer.cpp:279
#14 0x5661faa1 in main (argc=2, argv=0xffffd2d4) at /home/hazelnot/git/Vanilla-Conquer/tiberiandawn/startup.cpp:482
```

**Comment by hifi** [comment]
Can't reproduce this on Ubuntu 18.04, 64-bit build. Though I have gotten the same kind of fortify stack smashing crashes with RA.

**Comment by cg9999** [comment]
This is related to struct packing on 32 bit build (same as bug #191)

**Comment by hifi** [comment]
Ah, okay. #197 will fix both then I suppose.

**Comment by OmniBlade** [comment]
#197 has been merged into the main branch if you want to test and see if this has indeed fixed the issue?

**Comment by hazelnot** [comment]
The new build fixed it, yeah
