### ISSUE TITLE
[TD] Map editor crashes when pressing `d` after selecting an unit

### ISSUE THREAD

**Issue by giulianobelinassi** [TheAssemblyArmada/Vanilla-Conquer#671]
Open the map editor, select an unit, and press `d` on the keyboard. The map editor will crash with a segfault.

**Comment by giulianobelinassi** [comment]
```
Thread 1 "vanillatd" received signal SIGSEGV, Segmentation fault.
0x000055555630bd80 in ?? ()
(gdb) backtrace
#0  0x000055555630bd80 in ?? ()
#1  0x00005555555b332a in Debug_Key (input=7)
    at /home/giulianob/bagunca/Vanilla-Conquer/tiberiandawn/debug.cpp:255
#2  0x00005555555ad271 in Keyboard_Process (input=@0x7fffffffdcce: KN_D)
    at /home/giulianob/bagunca/Vanilla-Conquer/tiberiandawn/conquer.cpp:700
#3  0x00005555555ae5ca in Map_Edit_Loop ()
    at /home/giulianob/bagunca/Vanilla-Conquer/tiberiandawn/conquer.cpp:1707
#4  0x00005555555ac7d6 in Main_Game (argc=2, argv=0x7fffffffdfe8)
    at /home/giulianob/bagunca/Vanilla-Conquer/tiberiandawn/conquer.cpp:243
#5  0x0000555555664114 in main (argc=2, argv=0x7fffffffdfe8)
    at /home/giulianob/bagunca/Vanilla-Conquer/tiberiandawn/startup.cpp:454
(gdb) list
191	
192	    } while (command_char != 0 && command_char != 13 && argc < 20);
193	
194	    if (argc >= 20) {
195	        MessageBoxA(NULL, "Too many arguments on command line.", "Command & Conquer", MB_ICONEXCLAMATION | MB_OK);
196	        return -1;
197	    }
198	
199	    return main(argc, argv);
200	}
```
